/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fioreflowershop;

import da.ConsumerDA;
import da.CorporateDA;
import da.CustOrderDA;
import da.PaymentDA;
import entity.Custorder;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author waikang
 */
public class DeliveryPaymentList extends javax.swing.JFrame {
 PaymentDA paymentDA = new PaymentDA();
    /**
     * Creates new form DeliveryPaymentList
     */
    public DeliveryPaymentList() {
        initComponents();
        DisplayDeliveryPaymentList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "Customer Name", "Order ID", "Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("DELIVERY PAYMENT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeliveryPaymentList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeliveryPaymentList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeliveryPaymentList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeliveryPaymentList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeliveryPaymentList().setVisible(true);
            }
        });
    }
    public void DisplayDeliveryPaymentList(){
     Custorder custOrder = new Custorder();
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    Object rowData[] = new Object[4];
    CustOrderDA custOrderDA = new CustOrderDA();
    ConsumerDA consumerDA = new ConsumerDA();
           

    List<Custorder> custOrderList = custOrderDA.getAllRecord();
     for (Custorder custOrderList1 : custOrderList) {
         
         if(checkDate(custOrderList1.getDatedelivery())&&(custOrderList1.getStatus()).toUpperCase().equals("DELIVERY")){
             if(paymentDA.getRecordByCustorderID(custOrderList1.getCustorderid())==null&&consumerDA.getRecord(custOrderList1.getCustomerid().getCustomerid())!=null){
              rowData[0] = custOrderList1.getCustomerid().getCustomerid();
              rowData[1] = consumerDA.getRecord(custOrderList1.getCustorderid()).getFullname();
              rowData[2] = custOrderList1.getCustorderid();
              rowData[3] = "RM "+custOrderList1.getTotal();
              model.addRow(rowData);
             }
         }
     }
    }
     public boolean checkDate(Date deliveryDate){
        Date todayDate = new Date();
        boolean date;
        if(deliveryDate.getYear()== todayDate.getYear()){
            if(deliveryDate.getMonth() == todayDate.getMonth() ){
                if(deliveryDate.getDate() == todayDate.getDate() ){
                    date = true;
                }else{
                    date = false;
                }
            }else{
                date=false;
            }
        }else{
            date=false;
        }
        return date;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
